name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    uses: hongphuc110393/templates/.github/workflows/python-ci.yml@main
    with:
      project-name: code
